NeoCat/twicli

- plugins/thumbnail.js
Instagram の URL は https もあるようなので追加しました。
> plugin/thumbnail.js: Instagram https support

- plugins/tweets_around_tw.js
https://twitter.com/h0k0r0bi/statuses/574418450388414464 からツイートの前後のツイートを表示するように変更してみました。
> Add tweets_around_tw.js plugin

- plugins/notify_desktop.js
- plugins/stream.js
This enables twicli to notify with Web Notification API.
デスクトップ通知を実装するプラグインです。
(前回はバグを仕込んだままプルリクを送ってしまってすみませんでした…!)
> Add notify_desktop.js plugin

- plugins/embedsrc.js
embedsrc プラグインに RICOH THETA の全天球画像と動画を追加しました。
-   [RICOH THETA](https://theta360.com/ja/)
> plugins/embedsrc.js: Add RICOH THETA.

- plugins/notify_desktop.js
Stream APIのfollow情報に自分が行なったフォローも含まれることを失念しておりました… 大変失礼しました:disappointed:
> Show only followed notify.

- plugins/notify_desktop.js
リプライ通知を、リプライ(in_reply_toつき、もしくは先頭に@つき)とMention(それ以外のコメントRT、非公式RTなど)で分けました。
> devide Reply notice into Reply and Mention.

- twicli.js
ハッシュタグのパターンを Twitter Web Client に合わせて追加しました。
> Update hashtag pattern

- plugins/thumbnail.js
> thumbnail.js: Fix flickr

- plugins/find_rt.js
- twicli.js
一部のユーザーのフォローボタンが表示されないなどの現象に対応しました。
> Use user.id_str instead of user.id

- plugins/ioc_flags.js
各種目、国以外のチーム、式典などのハッシュタグに対応しました。
> Olympic2016 sports

- plugins/ioc_flags.js
> Olympic2016 japanese

- plugins/resolve_url.js
resolve_url.js の dlvr.it に \ が抜けていたようなので追加しました。
ご確認ください。
> plugins/resolve_url: Fix dlvr.it

- styles/default.css
- twicli.html
iPad で、埋め込み画像をタップして拡大したときにスクロールできるようにしました。
> Enable embedded picture scrolling on iPad

- lang.js
- twicli.js
長すぎるツイートをする前に confirm を出さない設定を追加しました。
\# Vivaldi のページパネル対策です。
> Add settings: confirm_too_long

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Add Olympic Athletes from Russia

- plugins/thumbnail.js
Instagram の URL に Username を含む場合でもサムネイルを表示できるようにしました。
> plugins/thumbnail.js: Support Instagram with username

- plugins/ioc_flags.js
さくらの絵文字を追補しました。
https://twitter.com/TwitterJP/status/1110195453327335424
> plugins/ioc_flags.js Cardcaptor Sakura

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Support quoted tweet

- plugins/ioc_flags.js
すみません。 #WorldPenguinDay の typo です...
> plugins/ioc_flags.js: typo #WorldPenguinDay

- plugins/thumbnail.js
- styles/default.css
- twicli.js
> plugins/thumbnail.js: Show thumbnail in quoted tweet

- plugins/thumbnail.js
引用ツイートに埋め込まれたメディアのサムネイル表示対応です。
> plugins/thumbnail.js: Show entities thumbnail in quoted tweet

- plugins/geomap.js
Google Map の利用に制約が出ているため、`plugins/geomap.js` で  OpenStreetMap を使うように変えました。
> Geomap replace Google Map with OpenStreetMap

- plugins/geomap.js
Leaflet と OpenStreetMap のリンクを新しいウィンドウで開くように調整しました。
> plugins/geomap.js: Open link inside attribution with new window

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Add Avengers variation

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Mother's day

- plugins/resolve_url.js
はてなブックマークのリダイレクト (`b.hatena.ne.jp/redirect?....`) を展開するようにしました。
> plugins/resolve_url.js: Hatena bookmark redirect

- plugins/ioc_flags.js
「君の名は。」「天気の子」のハッシュタグの絵文字を追加しました。
> plugins/ioc_flags.js: Add Shinkai's movies

- plugins/ioc_flags.js
> Click on emoji to search hashtag

- plugins/ioc_flags.js
> Emoji 20190716

- plugins/ioc_flags.js
`#天気の子` に加えて `#WeatheringWithYou` の絵文字を追加しました。
> plugins/ioc_flags.js: Add #WeatheringWithYou

- plugins/ioc_flags.js
`#Twitter夏祭り` などの絵文字を追加しました。
-   [#Twitterトレンド大賞 presents #Twitter夏祭り 開催が決定！](https://blog.twitter.com/ja_jp/topics/events/2019/twitter-trend-award-natsumatsuri-2019.html)
> plugins/ioc_flags.js: TwitterTrendAward_Summer_Emoji, etc

- plugins/tweet_url_reply.js
画像などの付いたツイートに jump アイコンが重複して表示されないようにしました。
e.g. <https://twitter.com/_wa_/statuses/1161911783558471680>
> Avoid duplicated jump icon

- plugins/ioc_flags.js
`#MyTwitterAnniversary` の絵文字を追加しました。
> plugins/ioc_flags.js: MyTwitterAnniversary

- twicli.js
いわゆる全角数字をハッシュタグのパターンに追加しました。
e.g. https://twitter.com/JGSDF_pr/status/1186575982083244033
> Add fullwidth digit to hashtag pattern

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Halloween2019_Emoji_GIF

- plugins/ioc_flags.js
> Dog day 2019 emoji

- plugins/lists.js
list のタブで次ページの取得時にエラーとなる場合があるのを修正しました。
> plugins/lists.js: Use id_str instead of id

- plugins/find_rt.js
- plugins/lists.js
- twicli.js
`plugins/find_rt.js` で `id` の代わりに `id_str` を使用するにしました。
また、`tw[]` から `max_id` の取得方法を統一しました。
> Use id_str instead of  id for max_id

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Update 'Twitterトレンド大賞'

- plugins/ioc_flags.js
`#ザチョコレート` などの絵文字を追加しました。
-   https://twitter.com/meiji_the_choco/status/1223410637750947840
-   https://twitter.com/meiji_the_choco/status/1224135413096271872
-   https://twitter.com/meiji_the_choco/status/1225010146293583874
> plugins/ioc_flags.js: Meiji_THEChocolate_JP_2020

- plugins/ioc_flags.js
下記の絵文字を追加しました。
-   国際女性デー
-   [ツイートは誰かの応援になる Twitter JapanとYahoo! JAPANが三陸地方応援企画を実施](https://blog.twitter.com/ja_jp/topics/company/2019/311_sanriku.html)
> Emoji International Women's Day 2020 and Sanriku Railway

- plugins/ioc_flags.js
キリンチャレンジカップ2019、三ツ矢サイダー、どうぶつの森などの絵文字を追加しました。
-   <https://twitter.com/_wa_/status/1241596041910054912>
> Emoji advertising 202003

- twicli.js
> Add WAVE DASH to hashtag pattern

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Nintendo_AnimalCrossing_2020_v2

- plugins/ioc_flags.js
`#TLを花でいっぱいにしよう` などの絵文字を追加しました。
> plugins/ioc_flags.js: CherryBlossom_2020_add

- plugins/ioc_flags.js
> plugins/ioc_flags.js: StayHome_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: StayHome_2020_WorldHealthDay_add1

- plugins/ioc_flags.js
> plugins/ioc_flags.js: EarthDay and TwitterForGood_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: #PressFreedom in Japanese

- plugins/search.js
- twicli.js
ユーザータブのプロフィールにある `t.co` の URL やハッシュタグをリンクに展開するようにしました。
> Expand url on profile

- plugins/ioc_flags.js
> Emoji together we can lets talk

- plugins/resolve_url.js
- twicli.js
サードパーティーの短縮 URL が展開できなくなっているのを修正しました。
> plugins/resolve_url.js: Support omitted scheme

- plugins/ioc_flags.js
> Ioc_flags.js: support profile

- plugins/ioc_flags.js
以下の絵文字を追加しました。
-   `#あたりまえにありがとう`
-   `#わたしたちにできること`
> plugins/ioc_flags.js: SocialGoodPJ_ThankYouEveryone_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: MothersDay2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: MSBuild_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: EarthDay_2020_ext_v2

- plugins/ioc_flags.js
> plugins/ioc_flags.js: WorldEnvironmentDay_ForNature_2020

- plugins/ioc_flags.js
GLOBAL PRIDE と 移民遺産月間 の絵文字を追加しました。
> plugins/ioc_flags.js: Pride_2020, MyImmigrantStory_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Pride_2020_AlwaysProud

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Fathers_Day_2020

- plugins/ioc_flags.js
> Emoji animal crossing nintendo 2020 new artwork

- .eslintrc.yml
- twicli.js
`errors` プロパティを参照しているオブジェクト名が違っていたのを直しました。
\# 何故か `application/rate_limit_status.json` が JSONP に対応していないため、rate limits は表示できないままですが...
> Wrong object name to get errors

- .eslintrc.yml
- oauth/twicli_oauth.js
- plugins/debug.js
- plugins/embedsrc.js
- plugins/find_rt.js
- plugins/insert_hashtag.js
- plugins/lists.js
- plugins/multi_account.js
- plugins/notify.js
- plugins/regexp.js
- plugins/reply_favicon.js
- plugins/resolve_url.js
- plugins/search.js
- plugins/shortcutkey.js
- plugins/shorten_url.js
- plugins/sound.js
- plugins/thumbnail.js
- plugins/translate.js
- plugins/tweet_url_reply.js
- plugins/tweets_around_tw.js
- twicli.js
ソースの変更がなるべく少なく済むようにしつつ、全体で極力 `eslint:recommended` が通るように ESLint の定義を更新してみました。
-   [Configuring ESLint - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/configuring#using-eslintrecommended)
> Apply `eslint:recommended` except some rules

- plugins/ioc_flags.js
> plugins/ioc_flags.js: WearAMask_2020_H2_2020

- twicli.js
メンションの大文字小文字を区別することなくリンクになるようにしました。
`@twicli` でも `@TWICLI` でもリンクになるようにしました。
> Ignore case of mention

- plugins/ioc_flags.js
`#Twitterトレンド大賞` `#TwitterTrendAward`  の絵文字を追加更新しました。
> plugins/ioc_flags.js: TwitterTrendAward_2020

- plugins/ioc_flags.js
> plugins/ioc_flag.js: Christmas_2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Paralympics_Sports_2021_

- plugins/ioc_flags.js
> Emoji spring highschool baseball 2022
