- plugins/debug.js
- plugins/followers.js
- plugins/lists.js
- plugins/multi_account.js
- plugins/outputz.js
- plugins/regexp.js
- plugins/search.js
- plugins/search2.js
- plugins/shortcutkey.js
- plugins/sound.js
- plugins/translate.js
- styles/default.css
- twicli.js
ユーザCSSを書いていて気になった点を修正してみました。量が多くて申し訳ないのですが…。
* アイコン画像など一部要素をdivやspanで囲い、background-imageとして描画するように
* type属性のないinput要素にtypeを設定
* checkboxをlabelで囲い、クリックの当たり判定を拡張
* ボタンなど操作可能な要素にオンマウスで指カーソルへ変わるように
> CSSを書きやすくなるように出力するHTMLを変更

- plugins/ioc_flags.js
e.g. https://twitter.com/khl/statuses/767760371763544064
ロシアのホッケーリーグの絵文字対応です。
`#КХЛ` に絵文字を表示するためには `twicli.js` のロシア語ハッシュタグ対応が別途必要ですが...
> ioc_flags: Add KHL

- twicli.js
user.description に @ から始まる文字列があった場合、それをユーザタブで開けるようにします（キャプチャの `@10sr`, `@10sr_bot` の部分）。
> Make screen_name in udesc a internal link

- plugins/embedsrc.js
- plugins/thumbnail.js
SlideShare の Mobile 版と埋め込みの URL に対応しました。
*   URL の右の ![->](/NeoCat/twicli/raw/master/images/jump.png) を続けてクリックしたときに前回表示したコンテンツが消えずに残る現象も対応 bcf24fe
*   埋め込み URL からサムネイル取得には未対応
*   エラー回避のみ実施 e5951f5
e.g.
-   `https://www.slideshare.net/Slideshare/10-million-uploads-our-favorites`
-   `https://www.slideshare.net/mobile/Slideshare/10-million-uploads-our-favorites`
-   `https://www.slideshare.net/slideshow/embed_code/21112125`
-   `https://www.slideshare.net/slideshow/embed_code/key/bP5rZdZymdBjp0`
> `embedsrc.js` and `thumbnail.js` support SlideShare mobile and embeded

- plugins/ioc_flags.js
平昌オリンピック 2018 向けに絵文字を追加更新しました。
-   [Follow the 2018 Winter @Olympics on Twitter](https://blog.twitter.com/official/en_us/topics/events/2018/Follow-the-2018-Winter-Olympics-on-Twitter.html)
-   [冬季 #オリンピック](https://blog.twitter.com/official/ja_jp/topics/events/2018/0209_sports.html)
> plugins/ioc_flags.js: Emoji for PyeongChang 2018

- plugins/embedsrc.js
SlideShare の URL の末尾に `/` を含んでいても埋め込み表示できるようにしました。
例: 
-   https://twitter.com/kdmsnr/statuses/968136694707896321
-   `https://www.slideshare.net/KyokoOmi/ss-78046479/`
> plugins/embedsrc.js: Support SlideShare URL contain slash

- plugins/thumbnail.js
Instagram の URL に `?utm_source=twitter` 等が付いていてもサムネイルを表示できるようにしました。
-   https://www.instagram.com/p/BiN2m6Bj-F2/?utm_source=twitter
> Enable thumbnail of Instagram with query string

- plugins/thumbnail.js
- plugins/tweet_url_reply.js
展開した画像やサムネイルの取得先が `http` のため表示できなくなっているのを修正しました。
> Avoid mixed content for some images

- plugins/embedsrc.js
- plugins/thumbnail.js
- plugins/translate.js
YouTube, ニコニコ動画、SlideShare の埋め込み表示と翻訳が https でも動作するようにしました。
また、SlideShare と Mobypicture のサムネイル表示の warning を抑止しました。
> Avoid mixed content for some embed and translator

- plugins/insert_hashtag.js
- plugins/ioc_flags.js
- twicli.js
各プラグインでハッシュタグのパターンを共通化しました。
\# 本体とプラグインの両方を変更したら `document.twicli_js_ver` などを更新した方が良いでしょうか...?
> Commonize hashtag pattern

- plugins/thumbnail.js
ツイートに改行が含まれる場合にサムネイルの位置がずれるのを直しました。
#97 の影響です。すみません!
> plugins/thumbnail.js: Adjust thumbnail position

- plugins/ioc_flags.js
`#令和元年` に対応しました。
\# さみだれですみません!
> plugins/ioc_flags.js: Reiwa first year

- plugins/ioc_flags.js
「こどもの日」の絵文字対応です。
-   [「#こどもの日」と「#母の日」はTwitter上で家族へ感謝の気持ちや愛を伝えませんか？](https://blog.twitter.com/ja_jp/topics/events/2019/childrensday_mothersday.html)
> plugins/ioc_flags.js: Children's day (Japan)

- plugins/ioc_flags.js
父の日の絵文字を追加しました。
- [6月16日（日）「 #父の日 」にTwitterで #お父さんありがとう を伝えよう](https://blog.twitter.com/ja_jp/topics/events/2019/fathersday2019.html)
> Emoji Fathers day

- plugins/ioc_flags.js
[7月17日は #世界絵文字デー](https://blog.twitter.com/ja_jp/topics/events/2019/World-Emoji-Day-2019.html) の絵文字を追加しました。
> plugins/ioc_flags.js: WorldEmojiDay_2019

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Wasabi_Emoji_2019

- plugins/ioc_flags.js
ハッシュタグ以外の絵文字も Twemoji (SVG) を使うようにしました。
> Replace native emoji with Twemoji (SVG)

- plugins/ioc_flags.js
`#StartSomethingPriceless` の絵文字対応です。
> [ラグビーワールドカップさんはTwitterを使っています: 「本日の @mastercard Player of the Matchに選ばれた松島幸太朗 @kouta121315🌸 トロフィーのプレゼンターは、ダン・カーター @DanCarter です 🇳🇿👑 #RWC2019 #JPNvRUS #RWC東京 #StartSomethingPriceless #POTM https://t.co/NqI9PewA6u」 / Twitter](https://twitter.com/rugbyworldcupjp/status/1175034531360989185)
> plugins/ioc_flags.js: StartSomethingPriceless_Rugby_World_Cup_Emoji

- plugins/ioc_flags.js
`#祝賀御列の儀` などの絵文字を追加しました。
-   [Twitter JapanさんはTwitterを使っています: 「昨晩は祝賀ムードに包まれるツイートがめだちました。 本日も「#祝賀御列の儀」 が午後3時00分からが行われます。ツイート時には以下のハッシュタグもあわせてご利用ください。国鳥の「キジ」が表示されます🇯🇵 #即位の礼 #祝賀御列の儀 #即位礼正殿の儀 #JapanEnthronement #JPNEnthronement https://t.co/y1ijCni27K」 / Twitter](https://twitter.com/TwitterJP/status/1193353369672241152)
> plugins/ioc_flags.js: EnthronementCeremony_Emoji_GIF

- plugins/ioc_flags.js
新年の絵文字を追加しました。
-   [年末年始はTwitterで 「#あけおめ」](https://blog.twitter.com/ja_jp/topics/events/2019/newyear-tweet-2019.html)
> plugins/ioc_flags.js: NewYearCelebration_Japan2019

- plugins/ioc_flags.js
オリンピック関係の絵文字を追加しました。
-   [#全員団結 絵文字が出ます](https://blog.twitter.com/ja_jp/topics/company/2019/danketsu-olympic.html)
> plugins/ioc_flags.js: JapanOlympicBrandTogether2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: WorldPressFreedomDay_2020

- plugins/thumbnail.js
Flicker のサムネイル読み込み時に console.warn が出ないようにしました。
> Supress warning mixed content when loading flicker

- plugins/shortcutkey.js
> plugins/shortcutkey.js: Support for omitted scheme URL

- plugins/ioc_flags.js
> plugins/ioc_flags.js: 2020_TokyoGubernatorialElection

- plugins/ioc_flags.js
`#世界難民の日` `#PLAYSTATION5` などの絵文字を追加しました。
> Emoji playstation ps5 and world refugees 2020

- plugins/ioc_flags.js
- twicli.js
下記のため、ツイート中のハッシュタグ、メンション、URL を正規表現によるマッチングに代え、`entities` から取得するようにしました。
-   正規表現のパターンで網羅できていない言語等のハッシュタグに対応
-   ヒンディー語等
-   存在しないユーザーのリンクを抑止
但しユーザー情報 (プロフィール) は、 `entities` にハッシュタグ、メンションの情報が含まれないため、従来通り正規表現によるマッチングのままです...
> Get hashtags mentions of tweet from entities

- plugins/ioc_flags.js
`#WWDC20` の絵文字を追加しました。
[WWDCのツイッターハッシュタグがカワイイ！ #WWDC20 | ギズモード・ジャパン](https://www.gizmodo.jp/2020/06/wwdc20-hashtag.html)
> Emoji wwdc 2020

- plugins/ioc_flags.js
`#WWDC20` の絵文字 6パターンに対応しました。
今後も増えそうですが...
> plugins/ioc_flags.js: WWDC_2020_V[1-6]

- plugins/geomap.js
`geomap.js` で使用する [Leaflet - a JavaScript library for interactive maps](https://leafletjs.com/) を 1.6.0 に更新しました。
> Leaflet 1.6.0

- plugins/ioc_flags.js
> plugins/ioc_flags.js: WWDC_2020_V[1-11]

- plugins/geomap.js
位置情報付きツイートで経緯度情報が全く含まれていない場合に `geomap.js` プラグイン無効時と同様の動作にフォールバックするようにしました。
例: https://twitter.com/_wa_/statuses/1278669562100084742
> plugins/geomap.js: Open link if there're no latitude and longitude

- plugins/ioc_flags.js
> plugins/ioc_flags.js: JP_FireworksDay_2020_BH

- plugins/resolve_url.js
サードパーティーの短縮 URL を使用していない場合でも `decodeURI()` を通すようにしてみました。
> Decode even if not shortened url

- plugins/ioc_flags.js
> plugins/ioc_flag.js: AppleEvent2020

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Tokyo2020_Olympics_add

- plugins/ioc_flags.js
`#COMINGOUTDAY` `#国際ガールズデー` `#APPLEEVENT` などの絵文字を追加更新しました。
> Emoji 20201008

- plugins/ioc_flags.js
> plugins/ioc_flags.js: AppleEvent_Nov_2020_BL_H2

- plugins/thumbnail.js
Twitpic のサムネイルの URL が使えなくなって暫く経つので `thumbnail.js` の対象から削除しました。
> plugins/thumbnail.js: Remove Twitpic because thumbnail URL expired

- plugins/ioc_flags.js
ISO-3166-1 alpha-2 の国名コードを使って国旗の絵文字を生成するようにしました。
> plugins/ioc_flags.js: Generate flags from alpha-2

- plugins/ioc_flags.js
`#あつまれどうぶつの森` 関連の絵文字が 404 Not found になっていたのを補正しました。
\# Twitter.com の絵文字表示は終了していますが…
> plugins/ioc_flags.js: AnimalCrossing_Nintendo_2020_NewArtwork_v2

- plugins/lists.js
- plugins/search.js
- twicli.js
`search.js` プラグインを使っていても、ユーザータイムラインのプロフィールにあるハッシュタグが twicli  のタブで開かないのを修正しました。
> Fix plugins/search.js not working in profile

- plugins/embedsrc.js
`www2.slideshare.net` の URL で共有されたスライドの表示に対応しました。
`www3.slideshare.net` などは `www.slideshare.net` にリダイレクトされるのですが、 `www2` だけリダイレクトされないようです。
> plugins/embedsrc.js: Support www2.slideshare.net

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Paralympics_2021, Paris_2024_Olympics

- twicli.js
ツイートに英数字などを含むときの文字数計算を修正し、最大280文字まで確認なしにツイートできるようにしました。
-   [より簡単に表現していただけるよう、ツイートの文字数を増やします](https://blog.twitter.com/official/ja_jp/topics/product/2017/Cramming-Experiment.html)
-   [Giving you more characters to express yourself](https://blog.twitter.com/en_us/topics/product/2017/Giving-you-more-characters-to-express-yourself)
> Show length based on character type

- twicli.js
引用リツイートのユーザーアイコンの `title` 属性で、ユーザーの  description に含まれる改行が `<br>` というテキストに置換されるのを抑止しました。
できれば改行に置換したいところですが、それだと改修が大がかりになりそうなので、引用 RT の場合のみ空白に置換するようにしました。
> Avoid replacing line breaks with <br> in user description of quoted RT.

- plugins/embedsrc.js
`plugins/embedsrc.js` で Gyazo を埋め込み表示すると `Refused to display 'https://i.gyazo.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` となるため、`iframe` に代えて `img` を使うようにしました。
関連: #206
> Avoid refusal from Gyazo by using <img>

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Fix typo TeamGEO

- plugins/ioc_flags.js
> plugin/ioc_flags.js: September_Event_2021

- plugins/ioc_flags.js
`#私たちの選挙` `#私たちの一票` を追加しました。また古い絵文字を更新しました。
> Emoji japan general election 2021

- plugins/ioc_flags.js
`#AppleEvent` `#NVIDIAGTC` などの絵文字を追加更新しました。
> plugins/ioc_flags.js: AppleEvent and NVIDIAGTC

- plugins/ioc_flags.js
`#COP26` `#ピクミンブルーム` などの絵文字を追加しました。
> plugins/ioc_flags.js: COP26_2021, PikminBloom_2021

- .eslintrc.yml
- plugins/embedsrc.js
- plugins/followers.js
- plugins/geomap.js
- plugins/regexp.js
- plugins/resolve_url.js
- plugins/shortcutkey.js
- plugins/translate.js
- plugins/tweet_url_reply.js
- styles/default.css
- twicli.js
`rep` のオーバーレイ表示で ↔️ ボタンが必要ないときに非表示にしました。
併せて DOM 要素の `className` の値を追加削除する仕組みをまとめました。
> Hide both button when not needed

- plugins/ioc_flags.js
`#チームジャパン` `#旧正月` などの絵文字を追加更新しました。
> Emoji beijing olympic and lunar new year 2022

- plugins/ioc_flags.js
> plugins/ioc_flags.js: Beijing_Winter_Olympics_Biathlon_2022

- plugins/ioc_flags.js
遅くなりましたが `#猫の日` などの絵文字を追加しました。
-   [2022年2月22日は特別な #猫の日](https://blog.twitter.com/ja_jp/topics/events/2022/2022-special-cat-day)
> plugins/ioc_flags.js: CatDay_white_2022

- plugins/ioc_flags.js
`#ワクチン完了` の絵文字を追加しました。
`#WomensHistoryMonth` などの絵文字を更新しました。
> Emoji vaccinated japan 2022

- plugins/ioc_flags.js
`#GoogleIO` `#MSBuild` の絵文字を更新しました。
> plugins/ioc_flags.js: Google_IO_Q2_2022, Microsoft_Build_May_2022

- plugins/ioc_flags.js
`#WWDC20` `#WeBelong` `#私たちの選挙` などの絵文字を追加更新しました。
> Emoji wwdc22 webelong pride japan upper house election jun 2022

- plugins/ioc_flags.js
`#投票しました` などの絵文字を追加しました。
-   [参院選 報道機関やNPOと連携し #私たちの選挙 を盛り上げる](https://blog.twitter.com/ja_jp/topics/events/2022/upperhouse-election)
> plugins/ioc_flags.js: Japan_Upper_House_Election_Voted_Jun_2022

- plugins/embedsrc.js
引用リツイートや画像などをオーバーレイ表示中に embedsrc.js 対応コンテンツを表示すると元のオーバーレイの中に混在してしまうのを修正しました。
> plugins/embedsrc.js: Prevent mixing of contents into overlay

- plugins/ioc_flags.js
> plugins/ioc_flags.js: AppleEvent_824_global_launch_Aug_2022

- .eslintrc.yml
- .github/workflows/eslint.yml
ESLint に `twitterAPI2` を対応させました。
併せて GitHub Actions を更新しました。
[GitHub Actions: All Actions will begin running on Node16 instead of Node12 | GitHub Changelog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
> Support twitterAPI2 in ESLint

- plugins/ioc_flags.js
twemoji で使用している CDN がシャットダウンしたため URL を更新しました。
Maxcdn has shut down, cdn not working anymore. · Issue #580 · twitter/twemoji https://github.com/twitter/twemoji/issues/580
> plugins/ioc_flags.js: Update CDN used by twemoji

- plugins/ioc_flags.js
Twemoji のライブラリを公式のフォーク版に更新しました。
-   [Twemojiが2023年になると表示されなくなる問題に対処する](https://zenn.dev/yhatt/articles/60ce0c3ca79994#%F0%9F%86%99-%E6%9B%B4%E6%96%B0%3A-2023%E5%B9%B41%E6%9C%8813%E6%97%A5)
> plugins/ioc_flags.js: Update CDN used in twemoji to official fork version

- twicli.js
ツイートのリトライが発生した時に `in_reply_to_status_id` が欠落するのを修正してみました。
GAE 経由でツイート時にたまに `net::ERR_ABORTED 500` になり、そのときに `in_reply_to_status_id` が欠落するようでした。
> Fix missing in_reply_to_status_id when retrying tweets
